# Generated by Django 5.1 on 2024-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
