# Generated by Django 5.1 on 2024-08-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comment_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
