# Generated by Django 5.1 on 2024-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('connexion', 'Login'), ('deconnexion', 'Logout')], max_length=20),
        ),
    ]
