# Generated by Django 5.1 on 2024-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Deconnexion')], max_length=20),
        ),
    ]
