# Generated by Django 5.1 on 2024-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('cc_num', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('city_pop', models.IntegerField()),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('merch_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('merch_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('trans_date_trans_time', models.DateTimeField()),
                ('trans_num', models.CharField(max_length=255)),
                ('unix_time', models.BigIntegerField()),
                ('is_fraud', models.BooleanField(default=False)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
