# Generated by Django 5.1 on 2024-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_territoire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='MONTANT_TRX',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
