# Generated by Django 5.1 on 2024-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_unix_time_transaction_chapitre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TERRITOIRE',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='UTILISATION',
            field=models.CharField(max_length=255),
        ),
    ]
