# Generated by Django 5.1 on 2026-09-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_montant_trx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='IS_COMPLIANT',
            new_name='IS_FRAUDULENT',
        ),
    ]
