# Generated by Django 5.1 on 2024-08-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='transaction',
        ),
    ]
